### ISSUE TITLE
Spec files created for enums, guard, etc...

### ISSUE THREAD

**Issue by BenDevelopment** [ZouYouShun/angular-spec-generator#1]
Your tool is very usefull, thank you.

But there is juste a little unexpected behaviour: it creates spec files for enums files, guards, and other file types which doesn't need spec file.

**Comment by ZouYouShun** [comment]
Hi @BenDevelopment , this is a simple tool to generate all spec files with
``` guard, component, service, directive, pipe```

currently, It doesn't have any configuration to setting that, I will add that recently.

**Comment by ZouYouShun** [comment]
Hi @BenDevelopment, I have published this feature with the configuration in `1.1.0`.

Now we can set `--type` to configure which types want to generate,
and set `--force` to replace exist spec files,
set `--clear` to clear spec files

more detial you can see in the document.
